### ISSUE TITLE
Storage of large data

### ISSUE THREAD

**Issue by leewujung** [aidanjohnson/dt7816#10]
- [x] Allow storage of large amount of data to an external drive
- [x] Provide a strategy that works for a 3-day unattended recording
   - This is a pretty stringent requirement, so make sure you have a strategy for figuring out bugs if recording fails
- [x] Identify an external drive for purchase for field work in August

**Comment by aidanjohnson** [comment]
This [paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5760034/pdf/pone.0190740.pdf) proposes a database system that I think we might find useful. They have a similar goal of citizen ecological science. 
***
Marshall HH, Griffiths DJ, Mwanguhya F, Businge R, Griffiths AGF, Kyabulima S, et al. (2018) Data collection and storage in long-term ecological and evolutionary studies: The Mongoose 2000 system. PLoS ONE 13(1): e0190740. https://doi.org/10.1371/journal.pone.0190740

**Comment by aidanjohnson** [comment]
### Background
Mostly for initial research purposes, I have found these miscellaneous documents to be 'inspirational' guidelines for selecting an SSD:

- [AMAR G3 Autonomous Acoustic Recorder by Jasco](https://static1.squarespace.com/static/52aa2773e4b0f29916f46675/t/590b9845e58c62a557ca3c0e/1493932121242/AMAR+Brochure_A4+v1.19.pdf): While these are for marine mammals, the same general design specifications apply.
- [AURAL M2 by Multi Electronique](http://www.multi-electronique.com/files/AURALspecsheet_EN.pdf): This brings up a tradeoff and constraint to consider when choosing an SSD:

   1. The capacity of the drive is proportional to energy consumption. 
   2. The data transfer rate must be sufficiently fast for the AIFF file creation.
- [Comparison of autonomous passive recorders](http://arquivos.info.ufrn.br/arquivos/20130912326cd81413429bafb6ca20bcf/SousaLimaetal2013_ARs.pdf): This led me to the two recorders above in addition to [OceanBase LADIN](http://www.ladin.usp.br/OBASE.html).

### Desired Characteristics

- At least 1 TB of data storage capacity.
   - _Tradeoff_: cost with capacity.
- Energy efficient such that it can be powered by the DT7816, which requires 5 Vdc from an external source--i.e. a battery.
   - _Tradeoff_ : capacity with energy consumption.
   - Type of battery: tradeoff of cost with energy capacity
- Data transfer rate >?.
   - Limited to speed of USB 2.0.
   - Limited to using USB and not SATA and its derivatives (unless use a converter which is likely powered).

### Possible Candidates
A setup guide on [Multi Electronique](http://www.multi-electronique.com/users.html) shows a WD Blue SATA HDD.

**Comment by aidanjohnson** [comment]
## Strategy

### Goal
A reliable 3-day unattended recording regime. 

### Considerations
- Recording duty cycle
- Battery constraints
- Storage constraints
- Field ease-of-use

#### Duty Cycle
Cycle on and off recording for sunset and sunrise (respectively). Sunset and sunrise times, which are calculated for longitude and latitude coordinates, can be buffered with a margin of safety (already implemented in software). A satisfactory safety margin—1800 s, 3600 s, etc. before sunset and after sunrise—will need to be selected.

#### Battery
For how long can the chosen battery power a running board that alternates between idle and recording? Battery must be selected such that it can power the board for at least 3 days, in order to satisfy most practical purposes.

#### Storage
See earlier discussion (above) on an external drive for the constraints faced. The energy consumption of the external drive must be factored into the minimum battery requirement calculation.

#### User Interface (UI)
The 8 LEDs on the board currently indicate if the given analog input channels are in operation. All turn off if no channels are active, i.e. the board is in idle and functioning normally or recording has failed. We will know if recording has failed if the current time falls within the on cycle and all channels are inactive. The use of these LEDs exhausts the built-in indicator functionality of the board. All additional indicators will less directly observable and therefore more difficult to use in the field. 

The current version of the software prints to the terminal each time a recording file is written to storage. This can be observed on a user laptop when the program is first run via the serial console. Any errors, fatal or otherwise, are printed to the terminal and the program shuts down. The only way to tell would be to connect to the board via USB-Serial or to notice the analog input channel LEDs are off during the on cycle (of course this observable state could mean other errors such as incorrect current local time or other improper duty cycle behaviour). Lastly, it is unclear whether connecting to the board after the program has been running will interrupt the program and reboot the board or will let the user view the board's current state. My suspicion is the latter. This will need to be verified once @funnyabc is finished with the CUnit tests and the board (and USB-Serial cable) is back in my possession. 

### DRAFT: Regime
1. Connect the board to the field laptop via USB-Serial and Ethernet once the board has been supplied power, connected to external storage, and positioned where desired. This will be the field user's opportunity to synchronise the local time clock and run the software `recorder`. The write path to the external storage will need to be entered into the C source code and compiled beforehand. The external drive should have the path `/media/...`.
2. The safety margin is to be specified in the command line when running the program. It can also be pre-defined and compiled beforehand.
3. Depending on the current local time, the board will either enter its idle or recording state. In the recording state the user should see the same number of LEDs flashing on as analog input channels selected. If the board is idling no LEDs should be lit. At this point the board can be left unattended.
4. **...WIP...**

**Comment by aidanjohnson** [comment]
@leewujung, any and all comments are welcome on the drafted recording regime/strategy. 😃
